### ISSUE TITLE
AttributeError: 'torch.dtype' object has no attribute 'type' -- What can cause this error?

### ISSUE THREAD

**Issue by garimss** [guanyingc/PS-FCN#1]
While running the command python eval/run_model.py --retrain data/models/PS-FCN_B_S_32.pth.tar --in_img_num 96 I get the below error:

Please help me how to remove this error here. 

TEST Iter [1/10] Epoch [1/30]
         [Time 64.936s] ToCPU: 57.957s| ToGPU: 0.105s| Forward: 4.040s|
Traceback (most recent call last):
  File "eval/run_model.py", line 23, in <module>
    main(args)
  File "eval/run_model.py", line 19, in main
    test_utils.test(args, 'test', test_loader, model, log, 1, recorder)
  File "D:\git_hub\PS-FCN\test_utils.py", line 33, in test
    log.printItersSummary(opt)
  File "D:\git_hub\PS-FCN\utils\logger.py", line 54, in printItersSummary
    print(opt['recorder'].iterRecToString(opt['split'], epoch))
  File "D:\git_hub\PS-FCN\utils\recorders.py", line 56, in iterRecToString
    strs += '{}: {:.3f}| '.format(k, np.mean(self.iter_rec[split][k]))
  File "C:\Users\Garima\Anaconda3\envs\PYTORCH\lib\site-packages\numpy\core\fromnumeric.py", line 3118, in mean
    out=out, **kwargs)
  File "C:\Users\Garima\Anaconda3\envs\PYTORCH\lib\site-packages\numpy\core\_methods.py", line 85, in _mean
    ret = ret.dtype.type(ret / rcount)
AttributeError: 'torch.dtype' object has no attribute 'type'

**Comment by garimss** [comment]
after I switch to pytorch0.4.0, test gets completed and shows below: 

 | TEST Iter [1/10] Epoch [1/30]
         [Time 29.446s] ToCPU: 23.115s| ToGPU: 0.098s| Forward: 4.086s|
         [ERR] n_err_mean: 6.620|

 | TEST Iter [2/10] Epoch [1/30]
         [Time 4.816s] ToCPU: 0.020s| ToGPU: 0.071s| Forward: 2.364s|
         [ERR] n_err_mean: 11.230|

 | TEST Iter [3/10] Epoch [1/30]
         [Time 4.606s] ToCPU: 0.017s| ToGPU: 0.057s| Forward: 2.348s|
         [ERR] n_err_mean: 15.865|

 | TEST Iter [4/10] Epoch [1/30]
         [Time 4.585s] ToCPU: 0.007s| ToGPU: 0.057s| Forward: 2.348s|
         [ERR] n_err_mean: 14.680|

 | TEST Iter [5/10] Epoch [1/30]
         [Time 4.578s] ToCPU: 0.007s| ToGPU: 0.056s| Forward: 2.333s|
         [ERR] n_err_mean: 11.906|

 | TEST Iter [6/10] Epoch [1/30]
         [Time 4.586s] ToCPU: 0.008s| ToGPU: 0.056s| Forward: 2.337s|
         [ERR] n_err_mean: 20.717|

 | TEST Iter [7/10] Epoch [1/30]
         [Time 4.690s] ToCPU: 0.007s| ToGPU: 0.056s| Forward: 2.341s|
         [ERR] n_err_mean: 27.790|

 | TEST Iter [8/10] Epoch [1/30]
         [Time 4.677s] ToCPU: 0.007s| ToGPU: 0.057s| Forward: 2.381s|
         [ERR] n_err_mean: 13.980|

 | TEST Iter [9/10] Epoch [1/30]
         [Time 4.711s] ToCPU: 0.008s| ToGPU: 0.057s| Forward: 2.400s|
         [ERR] n_err_mean: 14.190|

 | TEST Iter [10/10] Epoch [1/30]
         [Time 4.670s] ToCPU: 0.008s| ToGPU: 0.058s| Forward: 2.375s|
         [ERR] n_err_mean: 23.257|

---------- TEST Epoch 1 Summary -----------
         [ERR] n_err_mean: 16.024|

**Comment by garimss** [comment]
Now I would like to create a 3d for leg as in attached pic. How can i test on my own images?

**Comment by guanyingc** [comment]
Hi, it seems that the result you got (MAE: 16.024) is larger than that reported in paper? Could you shared the environment you used to run the code?

**Comment by guanyingc** [comment]
To test your own dataset, the easies way is to organize your dataset in a form similar to DiLiGenT benchmark and change the path to your dataset.
