### ISSUE TITLE
Question about max pooling

### ISSUE THREAD

**Issue by shsh9625** [guanyingc/PS-FCN#11]
Hi, I kinda have problem understanding the whole parts of your codes so would you please tell me where can I find the max pooling layer in it? By the way, thanks for your research :)

**Comment by guanyingc** [comment]
Hi, please kindly see the max-pooling layer in https://github.com/guanyingc/PS-FCN/blob/ffac2a3fdc395b2830c09783a09cfa6593ad0e63/models/PS_FCN.py#L85

**Comment by shsh9625** [comment]
Thanks for your help
