### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by Mbaqban** [guanyingc/PS-FCN#12]
Hi there, thanks for your codes
I was trying to train a new PS-FCN model with the training datasets following the steps just like you said but since l use google colab l have disk limitation on GPU(not premium) mode.
I want to ask if is possible to use only one of the two datasets for training and if it yes how far it would change the final results?
Actually I suppose this may decrease the accuracy of the model so what if I just use both datasets but cut off some of the views of each object? Do you think this might help?

**Comment by guanyingc** [comment]
Hi, in table 1 of the ECCV18 paper, we have shown that using both dataset achieved better results that only using the simple blobby dataset. 
<img width="1247" alt="Screen Shot 2020-08-25 at 9 27 14 AM" src="https://user-images.githubusercontent.com/8651158/91112297-518ebf00-e6b5-11ea-96cb-65f94c6339f6.png">

You might try first train only with the complex sculpture dataset. Or you can use half of both dataset to form a new dataset. However, I am not sure in what extent this will decrease the performance.

**Comment by Mbaqban** [comment]
> Hi, in table 1 of the ECCV18 paper, we have shown that using both dataset achieved better results that only using the simple blobby dataset.
> <img alt="Screen Shot 2020-08-25 at 9 27 14 AM" width="1247" src="https://user-images.githubusercontent.com/8651158/91112297-518ebf00-e6b5-11ea-96cb-65f94c6339f6.png">
> 
> You might try first train only with the complex sculpture dataset. Or you can use half of both dataset to form a new dataset. However, I am not sure in what extent this will decrease the performance.

Thanks for your help
