### ISSUE TITLE
Question obout about light intensity

### ISSUE THREAD

**Issue by HandsomeHehe** [guanyingc/PS-FCN#13]
Hi Chen, thanks for your code.
I have a question about the acquirement of the light intensity in your dataset.
Is it just a scale or physical quantity.
If it just a scale. And how do you get the physical lgiht intensity and convert it to scale.
I appreciate for lots of answers that you gave me previously.

**Comment by guanyingc** [comment]
Hi, In fact, the intensity value in DiLiGenT benchmark is measured as the image intensity of a near Lambertian surface. It is a 3-vector so that it can account for the light intensity for RGB color channel. Note that the absolute values of the intensity are not important, what matters is the relative intensity.

**Comment by HandsomeHehe** [comment]
Thanks.

> Note that the absolute values of the intensity are not important, what matters is the relative intensity

Firstly, we need to choose a benchmark intensity to  calculate the relative intensity.
If the benchmarks of the training dataset and the test dataset are different, will the effect be influenced?

**Comment by guanyingc** [comment]
Hi, the mean of "relative intensity" is among images of an object. For example, you can chose one of the image of the captured images as the reference. 

You don't need to choose a benchmark intensity.

**Comment by HandsomeHehe** [comment]
Hi, Chen. Thanks for your reply.
>  For example, you can chose one of the image of the captured images as the reference.

In the other word, there must be a vector = [1,1,1] in the light intensity file.
However, there is no such vector in the DiLiGenT dataset. I'm confused about this.

**Comment by guanyingc** [comment]
Sorry for the super late reply. You can divide the light intensities of all the images by the intensity of the first image. Then the intensity of the first image will be [1, 1,1].
