### ISSUE TITLE
About DataSets

### ISSUE THREAD

**Issue by zuiqingtian** [guanyingc/PS-FCN#14]
Hello, thank you for sharing. 
I have a few questions about the synthetic datasets. 
How do you get the groundtruth of the training set Blobby and Sculpture? Thank you again！

**Comment by guanyingc** [comment]
Hi, sorry for the late reply. We use Mitsuba for data rendering.  https://www.mitsuba-renderer.org/download.html

**Comment by zuiqingtian** [comment]
Thank you very much! I learned that the scenes are all synthesized by mitsuba, so is the groundtruth of the training set also synthesized by mitsuba? Thanks again for your answer!

**Comment by guanyingc** [comment]
Yes, you can save the normal using Mitsuba.

**Comment by guanyingc** [comment]
http://www.mitsuba-renderer.org/devblog/2014/02/mitsuba-0-5-0-released/

**Comment by zuiqingtian** [comment]
Ok! Thank you very much! I will try it!
