### ISSUE TITLE
Hello, I would like to inquire about the synthetic datasets.

### ISSUE THREAD

**Issue by zuiqingtian** [guanyingc/PS-FCN#15]
Hello, I want to ask, can I reproduce the rendering scene described in the paper exactly the same?

Because I noticed that for the objects in the synthetic data set in the paper, the BRDFS in each view randomly selects 2 of the 100 BRDFs.And the finally obtained image is under 64 illumination directions, which are also randomly sampled.

So does this mean that the original rendering scenes of these two synthetic datasets are no longer reproducible? 
Thank you for your reply!

**Comment by zuiqingtian** [comment]
Sorry, in addition, the merl dataset at the website    https://www.merl.com/brdf/     is no longer available for download. Can you provide merl data set download link? Thank you very much for your reply!

**Comment by guanyingc** [comment]
Hi,

Although I set the random seed to 0 during rendering, it might not be possible to render exactly the same dataset might not be possible. 

Please see https://drive.google.com/file/d/19fUBvRHWklg_vHLT8wuhL36ZmtYc7jOx/view?usp=sharing for a copy of MERL dataset.

A sample .xml file can be found in the following
`
<?xml version='1.0' encoding='utf-8'?>

<scene version="0.5.0">
    <default name="model" value="./blobs/blobs/obj/blob01.obj" />
    <default name="scale" value="0.8" />
    <default name="sc_x"  value="1" />
    <default name="sc_y"  value="1" />
    <default name="sc_z"  value="1" />
    <default name="x_rot" value="0" />
    <default name="y_rot" value="0" />
    <default name="z_rot" value="0" />
    <default name="tx1"   value="0" />
    <default name="ty1"   value="0" />
    <default name="tz1"   value="0" />
    <default name="tx"    value="0" />
    <default name="ty"    value="0" />
    <default name="tz"    value="0" />
    <default name="h"     value="512" />
    <default name="w"     value="512" />

    <integrator type="multichannel">
        <integrator type="field">
            <string name ="field" value="shNormal" />
            <spectrum name="undefined" value="0" />
            
        </integrator>
    </integrator>

	<shape type="sphere" id="obj1">
        <point name="center" x="$tx" y="$ty" z="$tz" />
        <float name="radius" value="$scale" />
	</shape>

	<sensor type="orthographic">
        <float name="farClip" value="55.864"/>
		<float name="nearClip" value="0.10864"/>
		<transform name="toWorld">
            <lookat target="0, 0, -14" origin="0, 0, -15" up="0, 1, 0"/>
		</transform>

		<sampler type="ldsampler">
			<integer name="sampleCount" value="64"/>
		</sampler>

		<film type="hdrfilm">
			<integer name="height" value="$h"/>
			<integer name="width" value="$w"/>

            <string  name="pixelFormat"  value="rgb"/>
            <string  name="channelNames" value="normal"/>
			<rfilter type="gaussian"/>
            <boolean name="banner" value="false"/>
		</film>
	</sensor>
</scene>
`

**Comment by zuiqingtian** [comment]
Thank you very much for your reply. your guidance is very helpful to me. 

So I combine this XML sample file with blobby dataset, merl dataset, sculpture dataset and MITSUBA renderer. Can I render the Synthetic datasets described in this article?

Because I noticed that the amount of data is very large, I downloaded it and unzipped it and it took me half a day, hhh.it may be troublesome to render manually. 

So I'm sorry to ask if there is a faster way to get this synthetic data set? The data set does not need to be as large as described in the paper, it is just a relatively small data set.

 Thank you very much again for your reply!

**Comment by guanyingc** [comment]
Oh, you might be using a remote internet disk. In my local hard disk, it takes around one hour to unzip the data.
I think you can just use a subset of the dataset. It might not be easy to render the dataset by yourself within a short time .

**Comment by zuiqingtian** [comment]
Thank you for your reply, your suggestion is very helpful to me!
