### ISSUE TITLE
Normal map to Depth map

### ISSUE THREAD

**Issue by yrtsao** [guanyingc/PS-FCN#18]
Hi,
Can you tell me how to let normal map become to depth map?
I tried to use the DGP method but it will let the depth map loss a lots detail features.
i really want to know,please help me.

**Comment by guanyingc** [comment]
Hi, you may refer to https://github.com/guanyingc/SDPS-Net/issues/2.

Or use the code in https://github.com/hoshino042/NormalIntegration.

**Comment by yrtsao** [comment]
> Hi, you may refer to [guanyingc/SDPS-Net#2](https://github.com/guanyingc/SDPS-Net/issues/2).
> 
> Or use the code in https://github.com/hoshino042/NormalIntegration.

Thanks for your help. I'm trying to use Matlab code to figure out this problem last night. But thank your help, I will try to use this Normal Integration method.
