### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by arkgao** [guanyingc/PS-FCN#19]
It seems the link in scripts/download_synthetic_datasets [http://www.visionlab.cs.hku.hk/data/PS-FCN/datasets](url) points to a corrupted .tgz file.  And these two dataset files are very small (196M and 49M). It shows that the files are updataed recently, so maybe something go wrong. Please check and fix it.
Thanks.

**Comment by guanyingc** [comment]
Thanks for the information, we have fixed it.
