### ISSUE TITLE
Cannot unzip the pre-trained model.

### ISSUE THREAD

**Issue by zuiqingtian** [guanyingc/PS-FCN#2]
![image](https://user-images.githubusercontent.com/48861451/69480646-541d6900-0e44-11ea-9895-4c11c5924e7a.png)

 I have some problems during the use, download with the pre-trained model you provided, showing a "corrupted". As shown in the figure, can you please tell me the solution? Thank you.

**Comment by guanyingc** [comment]
Hi, thanks for your interests. Oh, sorry for the naming of the file. In fact, you don't have to unzip the pre-trained model.  You just need to load the model by specifying the path.

**Comment by zuiqingtian** [comment]
> Hi, thanks for your interests. Oh, sorry for the naming of the file. In fact, you don't have to unzip the pre-trained model. You just need to load the model by specifying the path.

OK, thank you very much!
