### ISSUE TITLE
about the light direction

### ISSUE THREAD

**Issue by lih195** [guanyingc/PS-FCN#20]
hello，
I create the new dataset with blender and I used the dateset to test,but got a poor result. I would like to ask if the light direction refers to the coordinates of the light in the coordinate system (after normalization).
Looking forward to your reply。

**Comment by guanyingc** [comment]
Yes, the the coordinate origin should be at the object center.

Could you should me some results?

Please know that this method assumes an orthgrahic projection and distant directional lights. You may place a light far from the object.

You may also check the rendering setup for mitsuba https://github.com/guanyingc/PS-FCN/issues/17.

**Comment by lih195** [comment]
Thanks for your help. I used a point light before, and I now change it to directional light . And I want to know how far  the light is from the object?

> Yes, the the coordinate origin should be at the object center.
> 
> Could you should me some results?
> 
> Please know that this method assumes an orthgrahic projection and distant directional lights. You may place a light far from the object.
> 
> You may also check the rendering setup for mitsuba #17.

**Comment by guanyingc** [comment]
You might check the diligent paper for the real data capture setup.

![image](https://user-images.githubusercontent.com/8651158/199716762-4ba78956-61fa-4dd6-8060-5152d7ccb064.png)

**Comment by lih195** [comment]
> You might check the diligent paper for the real data capture setup.
> 
> ![image](https://user-images.githubusercontent.com/8651158/199716762-4ba78956-61fa-4dd6-8060-5152d7ccb064.png)
Thanks a lot!

**Comment by hmhan12** [comment]
Thanks a lot
