### ISSUE TITLE
coordinate system of light directions

### ISSUE THREAD

**Issue by FloralZhao** [guanyingc/PS-FCN#21]
Hi Guanying, thank you for sharing the synthetic data. I wonder the light directions represented by a vector are in which coordinate sysytem for both the synthetic data and DiLiGenT. More specifically, what are the axes directions? Are they x pointing to right, y pointing to up and z pointing towards the camera?

**Comment by guanyingc** [comment]
Hi, yes, x pointing to right, y pointing to up and z pointing towards the camera.

![image](https://user-images.githubusercontent.com/8651158/206115330-5ff51e15-0427-46c5-9a84-7fea001ae2a3.png)

**Comment by FloralZhao** [comment]
Thank you for the quick reply!
