### ISSUE TITLE
Cant  access the dataset as server is down

### ISSUE THREAD

**Issue by praveenk999** [guanyingc/PS-FCN#22]
http://www.visionlab.cs.hku.hk/data/PS-FCN/datasets/$dataset 

i cant access this site as server is down, pls help

**Comment by guanyingc** [comment]
Please kindly download it from https://pan.baidu.com/s/1WUVu9ibIBh4wM1shTXBuNw?pwd=snyc

**Comment by praveenk999** [comment]
I can't access

**Comment by praveenk999** [comment]
can u pls help, can u upload in any cloud and send?

**Comment by guanyingc** [comment]
Sorry, I am still figuring out a way to upload the dataset. It takes 20GB.

**Comment by guanyingc** [comment]
The dataset can be downloaded from the huggingface now. 
https://huggingface.co/Guanying/PhotometricStereo_Blobby_Sculpture_Dataset/tree/main
