### ISSUE TITLE
How do you get the sphere and bunny dataset?

### ISSUE THREAD

**Issue by ashisht96** [guanyingc/PS-FCN#4]
Can you please provide us with the ready sphere and bunny dataset?

**Comment by guanyingc** [comment]
Hi, we rendered the sphere and bunny dataset using Mitsuba and MERL BRDFs. You may download the dataset in http://www.visionlab.cs.hku.hk/data/PS-FCN/datasets/PS_Test_Sphere_Bunny.tgz. I just found it in my computer, and it should be the one used in the paper. Hope this help.
