### ISSUE TITLE
Question about the feature visualization

### ISSUE THREAD

**Issue by HandsomeHehe** [guanyingc/PS-FCN#7]
Sorry to trouble you.
Thank you for you code! 
Have you processed the feature before visualization, like normalization?
'cause i visualize the feature map after fusion and get 128 disorderly and unsystematic feature maps.

**Comment by guanyingc** [comment]
Yes, we have processed the features for visualization purpose. 
First, we clip the negative values of the feature, and then normalize the features to be in the range of [0, 1] by dividing them using the max value among the features. 
Last, we sort the features according to the sum of the feature values.

**Comment by HandsomeHehe** [comment]
Thanks again!
