### ISSUE TITLE
about making dataset : 

### ISSUE THREAD

**Issue by moonchildz** [guanyingc/PS-FCN#8]
Hi. I want to make a dataset with my own 3d models, just following your methods.
Can I know the program/ method you used? 
I appreciate for lots of answers that you gave me previously.

**Comment by guanyingc** [comment]
Hi, I rendered the dataset using the open source Mitsuba software.

Basically, I wrote a python script to configure the rendering setting and save the rendering commands into a bash script. Then I run the bash script to render the dataset.

**Comment by moonchildz** [comment]
Thanks for your answer. 
I was using 3DsMax before but I was having difficulty rendering random light/texture .
Do you think Mitsuba s/w is better than 3DsMax ?

**Comment by guanyingc** [comment]
Sorry, I haven't used 3DsMax before. I found that there are more people using Blender instead of Mitsuba.

**Comment by moonchildz** [comment]
Thanks for your comments
