### ISSUE TITLE
questions about the PS-FCN (B+S+32,16)

### ISSUE THREAD

**Issue by hezw2016** [guanyingc/PS-FCN#9]
Hey Guanying,

Thank you for sharing your wonderful code with us.
In your paper, I noticed that you provided the results when the input number is 16 in the testing phase. For each sample in DiliGenT, you firstly chose 16 random images from 96. Then, repeated 100 times. Finally, you calculated the average values. (Is this right?).

I guess you wrote a script to repeat 100 times and changed the "--seed" value in "base_opts.py" (or maybe the np.random.seed). Could you please share the script with me, or give me some suggestions? 

Best,
Zewei

**Comment by guanyingc** [comment]
Hi, Zewei,

In fact, we do it in this way. In the original code (not the public one), we have a `--repeat` option. In `DiLiGenT_main.py` we repeat `self.repeat` times (e.g., 100) for each object. Specifically, in `__len__()` function, we return `len(self.objs) * self.repeat`; in `__getitem__(self, index)` function, we convert the the input index to [0,9] by `index=index//self.repeat`.

Then you have to slightly modify the `test_utils.py` to average the results for every 100 test for each object. In this way, you don't need to run the algorithm from scratch for each test and keep changing the random seed.

Sorry that currently I am busy in something else and have no time to update the code to support repeat test mode. Hope this help.

**Comment by HandsomeHehe** [comment]
Hi, Guanying
Thank you for wonderful code.
I try the method as you said and the result is equal for each repeat. And I print the  `select_idx ` in `DiLiGent_main.py`. I notice that the select_idex of each object is not changing. That means the random seed is not changing.
Have you ever been in this situation?
Thanks again

**Comment by guanyingc** [comment]
Hi, thank you very much for pointing out.
After checking the code, I found that we have to set the random seed. 
```
def __getitem__(self, index):                                                                                                                                                  
     np.random.seed(index) 
     index = index // self.repeat                                                                                                                                               
     obj   = self.objs[index]  
```
The first few lines of `__getitem__()`  are something similar to the above codes.

**Comment by HandsomeHehe** [comment]
It works.
Thanks for helping
